# Generated by Django 2.0.1 on 2018-02-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='gru_salon',
            field=models.CharField(default='', max_length=10),
        ),
    ]
