# Generated by Django 2.0.1 on 2018-03-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20180305_1614'),
        ('maestros', '0003_grupos_gru_salon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DT_fecha', models.DateField(auto_now_add=True)),
                ('DT_descripcion', models.CharField(max_length=2000)),
                ('DT_actividadApoyo', models.CharField(max_length=2000)),
                ('DT_necesidades', models.CharField(max_length=2000)),
                ('DT_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumnos')),
                ('DT_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.maestros')),
            ],
        ),
        migrations.AddField(
            model_name='grupos',
            name='gru_grado',
            field=models.IntegerField(null=True),
        ),
    ]
