# Generated by Django 2.0.1 on 2018-04-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_auto_20180406_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='mae_nombre',
        ),
        migrations.AlterField(
            model_name='diariotrabajo',
            name='DT_maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padres.Profesor'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='gru_maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Maestro', to='padres.Profesor'),
        ),
        migrations.DeleteModel(
            name='maestros',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
