# Generated by Django 2.0.1 on 2018-03-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumnos_alu_tutores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='alu_tutores',
            field=models.ManyToManyField(to='padres.Tutor'),
        ),
    ]
