# Generated by Django 2.0.1 on 2018-03-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20180301_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='alu_fechaIngreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='alu_observaciones',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='alu_vigente',
            field=models.BooleanField(default=False),
        ),
    ]
