# Generated by Django 2.0.2 on 2018-03-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20180305_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='alu_foto',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
