# Generated by Django 2.0.2 on 2018-03-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumnos_alu_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='alu_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
