# Generated by Django 2.0.1 on 2018-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_auto_20180310_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='alu_foto',
            field=models.ImageField(default='media/default/default.jpeg', null=True, upload_to='media/fotosAlu'),
        ),
    ]
