# Generated by Django 2.0.1 on 2018-03-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_auto_20180312_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='1', max_length=24),
        ),
    ]
