# Generated by Django 2.0.1 on 2018-05-18 23:17

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_alumnos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='alu_genero',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='alu_vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default=builtins.id, max_length=24),
        ),
    ]
