# Generated by Django 2.0.2 on 2018-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_alumnos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='alu_genero',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='alu_vigente',
            field=models.BooleanField(default=True),
        ),
    ]
