# Generated by Django 2.0.1 on 2018-05-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_auto_20180518_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='alu_genero',
            field=models.CharField(default='Masculino', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='HQWL7Q25OJ9O7XKW7IJSHPFL', max_length=24),
        ),
    ]
