# Generated by Django 2.0.2 on 2018-05-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_auto_20180518_2322'),
        ('alumnos', '0013_auto_20180518_2138'),
    ]

    operations = [
    ]
