# Generated by Django 2.0.1 on 2018-05-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_auto_20180518_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='FCKFWMIFUF6HORYOMM9LEB3N', max_length=24),
        ),
    ]
