# Generated by Django 2.0.2 on 2018-05-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0015_auto_20180519_0035'),
        ('alumnos', '0015_merge_20180519_0018'),
    ]

    operations = [
    ]
