# Generated by Django 2.0.1 on 2018-05-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0016_merge_20180520_0251'),
        ('alumnos', '0017_auto_20180520_0503'),
    ]

    operations = [
    ]
