# Generated by Django 2.0.2 on 2018-05-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_merge_20180520_0628'),
        ('alumnos', '0018_merge_20180520_0629'),
    ]

    operations = [
    ]
