# Generated by Django 2.0.2 on 2018-05-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0019_merge_20180520_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='BMSMVDBJEVW25XMJB8K2D9Z4', max_length=24),
        ),
    ]
