# Generated by Django 2.0.1 on 2018-02-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_nombre', models.CharField(max_length=70)),
                ('tut_apellidoPaterno', models.CharField(max_length=70)),
                ('tut_apellidoMaterno', models.CharField(max_length=70)),
                ('tut_numero', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
