# Generated by Django 2.0.1 on 2018-03-05 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_correo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_descripcion',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_domicilio',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_parentesco',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tut_usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
