# Generated by Django 2.0.1 on 2018-03-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0002_auto_20180305_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_domicilio',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
