# Generated by Django 2.0.1 on 2018-04-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0003_auto_20180312_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='tut_usurio',
            field=models.CharField(default='papasito', max_length=18),
        ),
    ]
