# Generated by Django 2.0.1 on 2018-04-27 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0005_auto_20180426_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': (('is_tutor', 'Is_Tutor'),)},
        ),
        migrations.AlterField(
            model_name='profesor',
            name='pro_nombre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tut_usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
