# Generated by Django 2.0.1 on 2018-04-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0006_auto_20180427_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='tut_usuario',
            new_name='tut_nombre',
        ),
    ]
