# Generated by Django 2.0.1 on 2018-04-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0010_tutor_tut_apellidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'permissions': (('is_teacher', 'Is_Teacher'),)},
        ),
    ]
