# Generated by Django 2.0.1 on 2018-04-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0011_auto_20180427_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'permissions': (('is_tutorr', 'Is_Tutorr'),)},
        ),
    ]
