# Generated by Django 2.0.1 on 2018-05-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0013_auto_20180427_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tut_apellidos',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
