# Generated by Django 2.0.1 on 2018-05-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0014_auto_20180519_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='pro_nombres',
            field=models.CharField(default='s', max_length=80),
        ),
    ]
