from django import forms
from alumnos.models import alumnos
from padres.models import Tutor
import datetime

#class Alumno_Form(forms.ModelForm):
#	
#	model = alumnos
#	field = "__all__"
class Alumno_Form(forms.ModelForm):
	class Meta:
		model = alumnos
		fields = "__all__"
        
        #widgets = {
        #    'alu_nombre' = forms.TextInput(attrs = {'class': 'form-control'})
        #}
class Alumno_Chido(forms.Form):
	alu_nombre = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}))
	alu_genero = forms.CharField(label='Genero:', widget=forms.TextInput(attrs={'class':'form-control'}))
	alu_tutores = forms.ModelMultipleChoiceField(queryset=Tutor.objects.all(),label='Tutores:')
	alu_vigente = forms.BooleanField(label='Vigente:', widget=forms.TextInput(attrs={'class':'form-control'}))
	alu_fechaIngreso = forms.DateField(label='Fecha de Ingreso:',initial=datetime.date.today, widget=forms.TextInput(attrs={'type':'date'}))
	alu_observaciones = forms.CharField(label='Observaciones:', widget=forms.TextInput(attrs={'class':'form-control'}))
	slug = forms.CharField(label='Slug:', widget=forms.TextInput(attrs={'class': 'form-control'}))

class Alumno_Eva(forms.Form):
	E_maestro = forms.CharField(label='Maestro:', widget=forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}))
	E_alumno = forms.CharField(label='Alumno:', widget=forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}))
	E_fecha = forms.DateField(label='Fecha de evaluacion:',initial=datetime.date.today, widget=forms.TextInput(attrs={'type':'date'}))
	E_comparte = forms.IntegerField(label='Comparte libremente detalles cotidianos de su casa, escuela, comunidad:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3','min':'1','max':'3'}))
	E_apoya =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3','min':'1','max':'3'}))
	E_pregunta =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3','min':'1','max':'3'}))
	E_sugerencia =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_controla =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_cuida =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_espera =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_negocia =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_trabajaEquipo =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_respeta =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_cuidadoso =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_involucra =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_iniciativa =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_riesgo =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_estrategias=  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_seExpresa =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_mencionaNombre =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_mencionaDomicilio =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_expresaSentir  =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_exprasaSentimientos =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_recuerdaSusesos =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_solicitaPalabra =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_respetaTurno =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_explica =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_formulaPreguntas =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_comprendeTareas =  forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_solicitaAyuda = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_conversa = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_expresaInformacion = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_escucha = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_narra = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_creaCuentos = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_memorizaPoemas = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_realizaConteo = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_reconoce = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_plantea = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_sabeContar = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_sabeEscribir = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_izquierdaDerecha = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_arribaAbajo = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_llenoVacio = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_conoceDiasMeses = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_ayerMañana = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_describeSeresVivos = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_identificaSeresVivos = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_describeFenomeno = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_clasifica = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_SigueNormas = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_manipula = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_pruebas = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_reconoceExperimento = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_expresaIdeas = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_establecePresePasa = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_comparteInformacion = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_identificaAmenazas = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_escuchaYCanta = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_sigueRitmo = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_inventaCanciones = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_modifica = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_identificaDife = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_reproduceSecu = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_reconoceGeneroMu = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_baila = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_dramatizacion = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_participa = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_representa = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_improvisa = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_manipulaMateriales = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_observaRe = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_memorizaAutor = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_desplaza = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_muestra = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_participaJuegos = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_jalaEmpuja = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_explora = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_construye = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_arma = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_practica = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_conocePractica = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_conocePropone = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_reconoceAmbien = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))
	E_identificaPeligro = forms.CharField(label='Nombres:', widget=forms.TextInput(attrs={'type':'number','min':'1','max':'3'}))